INSERT INTO student VALUES (1, 'Egor', 'Vidyakin', 16, 1),
                           (2 , 'Anatoliy', 'Pushkarev', 16, 1),
                           (3 , 'Nikolay', 'Moskvin', 17, 1),
                           (4 , 'Ekaterina', 'Potexina', 19, 1),
                           (5 , 'Rostislav', 'Glizerin', 20, 1),
                           (6 , 'Denis', 'Egoshin', 14, 2),
                           (7 , 'Kamil', 'Kandaev', 13, 2),
                           (8 , 'Mixail', 'Mukhorin', 12, 2),
                           (9 , 'Alexandra', 'Sayapina', 10, 2),
                           (10 , 'Danil', 'Xydyakov', 22, 2),
                           (11 , 'Artemiy', 'Arsibekov', 14, 3),
                           (12 , 'Kirill', 'Glushkov', 15, 3),
                           (13 , 'Pavel', 'Danilov', 16, 3),
                           (14 , 'Elena', 'Kislichina', 16, 3),
                           (15 , 'Mariya', 'Poptcova', 17,3 ),
                           (16 , 'Ivan', 'Radishkin', 18, 4),
                           (17 , 'Darya', 'Yskova', 19, 4),
                           (18 , 'Alexander', 'Pasternak', 19, 4),
                           (19 , 'Rinat', 'Gaysin', 18, 4),
                           (20 , 'Danil', 'Nikitin', 18, 4),
                           (21 , 'Danil', 'Kamalov', 18, 5),
                           (22 , 'Egor', 'Suchencov', 17, 5),
                           (23 , 'Konstantin', 'Pashibekov', 15, 5),
                           (24 , 'Maksim', 'Semenov', 16, 5),
                           (25 , 'Konstantin', 'Razumov', 14, 5),
                           (26 , 'Daria', 'Nechaeva', 18, 6),
                           (27 , 'Anastasiya', 'Zolotoreva', 14, 6),
                           (28 , 'Maxim', 'Kovenkov', 14, 6),
                           (29 , 'Dmitriy', 'Zolotov', 15, 6),
                           (30 , 'Sergey', 'Zolotov', 44, 6),
                           (31 , 'Stas', 'Volosatov', 45, 7),
                           (32, 'Lenar', 'Yusupov', 35, 7),
                           (33, 'Yura', 'Pasternak', 34, 7),
                           (34, 'Arina', 'Komissarova', 12, 7),
                           (35, 'Alina', 'Podorozhinikova', 14, 7),
                           (36, 'Katerina', 'Borodina', 16, 8),
                           (37, 'Anton', 'Dosta', 17, 8),
                           (38, 'Marina', 'Zvereva', 17, 8),
                           (39, 'Valera', 'Nosonov', 14, 8),
                           (40, 'Egor', 'Rusinov', 24, 8),
                           (41, 'Semen', 'Laletin', 18, 9),
                           (42, 'Artemiy', 'Nazarov', 17, 9),
                           (43, 'Danil', 'Goncharov', 30, 9),
                           (44, 'Danila', 'Zhubrin', 21, 9),
                           (45, 'Artemiy', 'Zavoiskix', 20, 9);